### ISSUE TITLE
Build failing when I wrap component  with block 😢 

### ISSUE THREAD

**Issue by Jsince99** [aidenybai/million-react#10]
I have following code
```
import React from 'react';
import { block } from 'million/react';

const A : React.FC =()=>{
return <h1> HI</h1>;
};

export const ABlock = block(A);
```

I added _`million.vite()`  in the plugins array too. But getting the following error. If I don't use block it's working fine.

````
[vite-plugin-pwa:build] [vite]: Rollup failed to resolve import "react-dom/client" from "../../../node_modules/.pnpm/million@2.4.8/node_modules/million/dist/react.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "react-dom/client" from "../../../node_modules/.pnpm/million@2.4.8/node_modules/million/dist/react.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///Users/sravanth/Documents/mono/node_modules/.pnpm/vite@3.0.4_sass@1.54.0_terser@5.16.2/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:43609:19)
    at onwarn (file:///Users/sravanth/Documents/mono/node_modules/.pnpm/vite@3.0.4_sass@1.54.0_terser@5.16.2/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:43399:13)
    at Object.onwarn (file:///Users/sravanth/Documents/mono/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
    at ModuleLoader.handleResolveId (file:///Users/sravanth/Documents/mono/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
    at file:///Users/sravanth/Documents/mono/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22119:26

```
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Jsince99** [comment]
tagging @aidenybai for quick attention 👀

**Comment by Jsince99** [comment]
i was using react version <18. that's the reason for the errors. after upgrading it's working fine.
